config/routes.rb
require "sidekiq/web"


Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"
  resources :restaurants 
  resources :reviews do
    resources :comments
  end
  
  devise_for :users
  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user
  validates :comment, presence: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_one_attached :media
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  has_one_attached :media
  has_many :comments, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_uniqueness_of :username
  validates_presence_of :username
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update, :destroy, :show]
  before_action :set_review

  def new
    @comment = Comment.find(params[:review_id])
  end

  def create
    @comment = @review.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      
      if @comment.save
        ReviewMailer.with(comment: @comment, review: @review).new_response.deliver_now
        format.turbo_stream
        format.html { redirect_to review_path(@review), notice: "Comment created successfully" }
      else
        format.turbo_stream
        format.html { redirect_to review_path(@review), alert: "Comment could not be created." }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.turbo_stream
        format.html { redirect_to review_path(@review), notice: "Comment create successfully" }
      else
        format.turbo_stream
        format.html { redirect_to review_path(@review), alert: "Comment could not be created." }
      end
    end
  end

  def destroy
    @comment.destroy
    redirect_to reviews_path(@review)
  end


  private

    def set_review
      @review = Review.find(params[:review_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:comment, :review_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]

  # GET /restaurants or /restaurants.json
  def index
    if params[:category].blank?
			@restaurants = Restaurant.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@restaurants = Restaurant.where(:category_id => @category_id).order("created_at DESC")
		end
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /restaurants/1/edit
  def edit
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :user_id, :media, :category_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to review_url(@review), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to review_url(@review), notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:title, :rating, :body, :media,:restaurant_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_svg(name, options = {})
        options[:title] ||= name.underscore.humanize
        options[:aria] = true 
        options[:nocomment] = true 
        options[:class] = options.fetch(:styles,"fill-current text-gray-500")
        filename = "#{name}.svg"    
        inline_svg_tag(filename, options)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  
    def inject_feed_ad(index)
      unless user_signed_in? 
        if((index + 1) % 3 == 0)
          render partial: "feed_ad"
        end
      end
    end
  
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag comment do %>
  <div class="border p-4 rounded my-4 flex items-start">

    <div>
      <p class="font-semibold"><%= comment.user.username %></p>
      <div class="prose prose-orange"><%= comment.comment %></div>

      <% if user_signed_in? && current_user.id == comment.user_id %>
        <div class="flex items-end space-x-3">
          <%= link_to "Edit comment", edit_review_comment_path(comment.review, comment), class: "text-orange-600 underline" %>

          <%= button_to "Delete comment", review_comment_path(comment.review, comment), method: :delete, class: "text-orange-600 underline"
    %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag @comment do %>
  <%= render "comments/form", comment: @comment %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodLoverz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="bg-gray-200 relative h-screen overflow-x-hidden">

    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div class="bg-red-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
        </div>
      <% end %>
      <% if type == "notice" %>
        <div class="bg-green-500">
          <div class="container px-2 mx-auto py-4 text-white text-center font-medium font-sans"><%= message %></div>
        </div>
      <% end %>
    <% end %>

    <nav class="bg-white py-2 border-b border-gray-400" role="navigation" aria-label="main navigation">

      <div class="flex flex-wrap items-center justify-center lg:justify-start lg:content-center px-4 lg:px-6 lg:space-x-3 lg:py-0 py-3">

          <%= link_to root_path, class:"leading-normal no-underline text-gray-800 my-2 md:my-0 hover:text-orange-600 lg:w-auto w-full lg:text-left text-center" do %>
            <h1 class="text-lg pr-2 uppercase font-bold">FoodLoverZ</h1>
          <% end %> 

          <div class="flex flex-wrap justify-start w-full lg:w-2/3 flex-1">

            <div class="flex flex-wrap items-center lg:flex-1 lg:space-x-6 lg:w-auto     w-full">
              

              <div class="lg:flex-1 lg:w-auto w-full lg:mb-0 mb-3">
                <div class="relative">
                  <input class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight pl-9" id="search" type="text" placeholder="Search restaurant's">
                  <div class="pointer-events-none absolute inset-y-5 left-2 flex items-center">
                    <%= render_svg "icons/search", styles:"stroke-current w-5 h-5 text-gray-700"%>
                  </div>
                </div>
              </div>

              
              
              <div class="lg:w-1/4 w-full lg:mb-0 mb-3">

                <div data-controller="dropdown" class="rounded bg-white text-gray-700 ml-1 hover:bg-gray-50 relative">

                  <%= link_to "#", class: "border no-underline flex items-center justify-between text-gray-700 py-3 px-3 rounded border-gray-400", data: { action: "click->dropdown#toggle click@window->dropdown#hide" } do %>
                    <span class="font-semibold text-sm"><%= content_for?(:category_label) ? yield(:category_label) : "Select a category" %></span>

                    <div class="pointer-events-none absolute inset-y-5 right-2 flex items-center">
                      <%= render_svg "icons/chevron-down", styles: "fill-current w-5 h-5 text-gray-500" %>
                    </div>
                  <% end %>

                  <ul class="hidden absolute top-10 left-0 bg-white min-w-[250px] border border-gray-400 rounded shadow-lg divide-y" data-dropdown-target="menu">
                    <% Category.all.each do |category| %>
                      <li class="<%= 'active' if params[:category] == category.name %>">
								        <%= link_to category.name, restaurants_path(category: category.name), class: "bg-white rounded px-4 py-2 hover:bg-orange-50 hover:text-orange-700 flex items-center group" %>
							        </li>
						        <% end %>
                  </ul>

                </div>
              </div>
            
              <%= link_to "Restaurants",restaurants_path, class:"inline-block px-6 py-2.5 bg-orange-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-orange-700 hover:shadow-lg focus:bg-orange-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-orange-800 active:shadow-lg transition duration-150 ease-in-out" %>
				      
            </div> 
          
            <div class="lg:pl-6 flex flex-wrap items-center justify-end pt-4 lg:pt-0">
              <div class="mr-3">

                  <% if user_signed_in? %>
                    <%= link_to new_review_path  do %>
                      <%= render_svg 'icons/create' %>
                  <% end %>

                  <% else %>
                    <%= link_to "Login", new_user_session_path, class:"font-semibold text-lg py-3 rounded cursor-pointr no-underline text-gray-800 border bordar-gray-400 hover:bg-gray-100 font-medium py-2 px-4 rounded text-sm mr-2" %>
                    <%= link_to "Sign up", new_user_registration_path, class: "font-semibold text-lg py-3 rounded cursor-pointr no-underline bg-orange-600 text-white hover:bg-orange-700 font-medium py-2 px-4 rounded text-sm" %>
                  <% end %>
              </div>

              <% if user_signed_in? %>
              <div data-controller="dropdown" class="rounded bg-white border border-gray-400 text-gray-600 ml-1 hover:bg-gray-100 py-0 px-4">

                <%= link_to "#", class: "no-underline flex justify-between text-sm tracking-wide items-center font-semibold select-none py-3", data: { action: "click->dropdown#toggle click@window->dropdown#hide" } do %>
                  <%= current_user.username ||= current_user.email  %>
                  <%= render_svg "icons/chevron-down", styles: "ml-2 w-4 h-4 text-gray-600" %>
                <% end %>
                <div class="relative">
                  <ul class="hidden absolute top-2 -right-4 bg-white min-w-[200px] border border-gray-400 rounded shadow-lg" data-dropdown-target="menu">
                    <li>
                      <%= link_to "#", class: "hover:bg-orange-50 hover:text-orange-600 text-gray-600 no-underline block py-3 px-4 flex items-center group rounded-t" do %>
                        <%= render_svg "icons/user" ,styles: "w-5 h-5 fill-current group-hover:text-orange-600 text-gray-600 mr-3" %>
                        My profile
                      <% end %>
                    </li>
                    <li>
                      <%= link_to edit_user_registration_path, class: "hover:bg-orange-50 hover:text-orange-600 text-gray-600 no-underline block py-3 px-4 flex items-center group" do %>
                        <%= render_svg "icons/settings" ,styles: "w-5 h-5 fill-current text-gray-600 mr-3 group-hover:text-orange-600" %>
                        Account settings
                      <% end %>
                    </li>
                    <li>
                      <%= button_to destroy_user_session_path, method: :delete, class: "hover:bg-orange-50 hover:text-orange-600 text-gray-600 no-underline block py-3 px-4 flex items-center group w-full rounded-b" do %>
                        <%= render_svg "icons/signout", styles: "w-5 h-5 fill-current text-gray-600 mr-3 group-hover:text-orange-600" %>
                        Sign out
                      <% end %>
                    </li>
                  </ul>

                </div>
              </div>
            <% end %>

              </div>
            </div>
          </div>

      </div>
    </nav>

    <div class="container mx-auto py-6">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">

  <% if restaurant.media%>
      <div class="w-2/12">
        <%= link_to restaurant do %>
          
            <%= image_tag restaurant.media, alt:"#", class: "" %>
          
        <% end %>
      </div>
    <% end %>

  <div class="flex flex-wrap items-center justify-between">
    <% if user_signed_in? && current_user.id == restaurant.user_id %>
            <div class="pt-4 flex flex-wrap items-center space-x-4">
              <%= link_to edit_restaurant_path(restaurant), class: "no-underline" do %>
                <%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-400 w-5 h-5 hover:text-orange-600" %>
              <% end %>

              <%= button_to restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure you want to delete this review?" },  class: "no-underline block mt-px" do %>
                <%= render_svg "icons/delete", title: "Delete", styles: "fill-current text-gray-400 w-5 h-5 hover:text-orange-600" %>
              <% end %>
            </div>
      <% end %>
  </div>

  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= restaurant.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= restaurant.category.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Address:</strong>
    <%= restaurant.address %>
  </p>

  
</div>

app/views/restaurants/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing restaurant</h1>

  <%= render "form", restaurant: @restaurant %>

  <%= link_to "Show this restaurant", @restaurant, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to restaurants", restaurants_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/restaurants/index.html.erb
<% content_for :primary_content do %>
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Restaurants</h1>
  </div>

  <div class="w-2/8 grid grid-cols-4">
    
		<% @restaurants.each do |restaurant| %>
			<%= link_to restaurant, class:"m-4 text-center font-semibold" do %>
          
            <%= image_tag restaurant.media, alt:"#", class: "mb-2" %>
          
          <%= restaurant.name%>

            <%= render_svg "icons/conversation", styles: "w-4 h-4 fill-current text-gray-400 group-hover:text-orange-600" %>
            <p class="group-hover:text-orange-600"><%= pluralize(restaurant.reviews.size, 'reviews') %></p>
   
      <% end %>	
      
		<% end %>

	</div>

</div>
<%end%>

<% content_for :secondary_content, class:"flex justify-between" do%>
  <div class="px-4 pt-4 pb-4">
    <% if user_signed_in? %>
      <h3 class="font-bold text-lg mb-4">Welcome, <%= current_user.username %></h3>

      <%= link_to "Create review", new_review_path, class: "text-orange-600 underline mr-2" %>

      <%= link_to "Create restaurant", new_restaurant_path, class: "text-orange-600 underline" %>

    <% else %>
      
      <h3 class="font-bold text-lg mb-4">Explore</h3>
        <%= link_to "Create review", new_review_path, class: "text-orange-600 underline mr-2" %>

        <%= link_to "Create restaurant", new_restaurant_path, class: "text-orange-600 underline" %>
    <% end %>

  </div>
  
<% end %>

<%= render "basic_layout"%>

app/views/restaurants/show.html.erb
<% content_for :primary_content do %>
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @restaurant %>
      
  
   
  <ul class="divide-y list-none">
    <p class="font-semibold">"<%=@restaurant.name%>" Reviews</p>
    <% @restaurant.reviews.each_with_index do |review, index| %>
      <%= inject_feed_ad(index) %>
      <%= render "reviews/review", review: review %>
    <% end %>
  </ul>
  

  </div>
</div>
<%end%>

<% content_for :secondary_content, class:"flex justify-between" do%>
  <div class="px-4 pt-4 pb-4">
    <% if user_signed_in? %>
      <h3 class="font-bold text-lg mb-4">Welcome, <%= current_user.username %></h3>

      <%= link_to "Create review", new_review_path, class: "text-orange-600 underline mr-2" %>

      <%= link_to "Create restaurant", new_restaurant_path, class: "text-orange-600 underline" %>

    <% else %>
      
      <h3 class="font-bold text-lg mb-4">Explore</h3>
        <%= link_to "Create review", new_review_path, class: "text-orange-600 underline mr-2" %>

        <%= link_to "Create restaurant", new_restaurant_path, class: "text-orange-600 underline" %>
    <% end %>

  </div>
  
<% end %>



<%= render "basic_layout"%>

app/views/reviews/_review.html.erb
<li class="list-none" id="<%= dom_id review%>">
  <div class="px-2 py-3 flex items-center flex-wrap">

    <% if review.media %>
      <div class="w-2/12">
        <%= link_to review do %>
          
            <%= image_tag review.media, alt:"#", class: "" %>
          
        <% end %>
      </div>
    <% end %>

    <div class="flex-1 <%= "pl-4" if review.media%>">
      <h3 class="mb-1 flex flex-wrap items-center text-xl">
        <%= link_to review.title, review, class: "no-underline font-semibold items-center text-xl hover:text-orange-600" %>

      </h3>

      <p class="font-mono text-sm text-gray-600 group hover:text-orange-600 mb-2">
        Restaurant - <%= link_to review.restaurant.name, restaurant_path(review.restaurant), class: "group-hover:text-orange-600 font-semibold" %> -
      </p>

      <% if review.body? %>
        <div class="text-base text-gray-700">
          <%= truncate(review.body, length: 140) %>
        </div>
      <% end %>

      <p class="text-sm text-gray-600 mb-3">Posted by @<%= link_to review.user.username,review_path(review), class: "underline font-semibold" %> <%= time_ago_in_words(review.created_at) + " ago" %> </p>



       <div class="flex flex-wrap items-center justify-between">

       <div class="mt-3 flex-1">
          <%= link_to review_path(review, anchor: "comment_section"), class: "flex items-center space-x-3 group" do %>
            <%= render_svg "icons/conversation", styles: "w-4 h-4 fill-current text-gray-400 group-hover:text-orange-600" %>
            <p class="group-hover:text-orange-600"><%= pluralize(review.comments.size, 'comment') %></p>
          <% end %>
        </div>
        

        <% if user_signed_in? && current_user.id == review.user_id %>
          <div class="pt-4 flex flex-wrap items-center space-x-4">
            <%= link_to edit_review_path(review), class: "no-underline" do %>
              <%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-400 w-5 h-5 hover:text-orange-600" %>
            <% end %>

            <%= button_to review_path(review), method: :delete, data: { confirm: "Are you sure you want to delete this review?" },  class: "no-underline block mt-px" do %>
              <%= render_svg "icons/delete", title: "Delete", styles: "fill-current text-gray-400 w-5 h-5 hover:text-orange-600" %>
            <% end %>
          </div>
        <% end %>
      </div>


    </div>
  </div>
</li>

app/views/reviews/index.html.erb
<% content_for :primary_content do %>


  
  <h1 class="font-semibold">Reviews</h1>
  <div id="reviews">
    <ul class="divide-y list-none">
      <% @reviews.each do |review| %>
        <%= render review %>
      <% end %>
    </ul>
  </div>

  
<% end %>
  

  
<% content_for :secondary_content, class:"flex justify-between" do%>
  <div class="px-4 pt-4 pb-4">
    <% if user_signed_in? %>
      <h3 class="font-bold text-lg mb-4">Welcome, <%= current_user.username %></h3>

      <%= link_to "Create review", new_review_path, class: "text-orange-600 underline mr-2" %>

      <%= link_to "Create restaurant", new_restaurant_path, class: "text-orange-600 underline" %>

    <% else %>
      
      <h3 class="font-bold text-lg mb-4">Explore</h3>
        <%= link_to "Create review", new_review_path, class: "text-orange-600 underline mr-2" %>

        <%= link_to "Create restaurant", new_restaurant_path, class: "text-orange-600 underline" %>
    <% end %>

  </div>
  
<% end %>

<%= render "basic_layout"%>

app/views/reviews/show.html.erb
<li class="list-none" id="<%= dom_id @review%>">
  <div class="px-2 py-3 flex items-center flex-wrap">

    <% if @review.media %>
      <div class="w-2/12">
        <%= link_to @review do %>
          
            <%= image_tag @review.media, alt:"#", class: "" %>
          
        <% end %>
      </div>
    <% end %>

    <div class="flex-1 <%= "pl-4" if @review.media%>">
      <h3 class="mb-1 flex flex-wrap items-center text-xl">
        <%= link_to @review.title, @review, class: "no-underline font-semibold items-center text-xl hover:text-orange-600" %>

      </h3>

      <p class="font-mono text-sm text-gray-600 group hover:text-orange-600 mb-2">
        Restaurant - <%= link_to @review.restaurant.name, restaurant_path(@review.restaurant), class: "group-hover:text-orange-600 font-semibold" %> -
      </p>

      <% if @review.body? %>
        <div class="text-base text-gray-700">
          <%= truncate(@review.body, length: 140) %>
        </div>
      <% end %>

      <p class="text-sm text-gray-600 mb-3">Posted by @<%= link_to @review.user.username,review_path(@review), class: "underline font-semibold" %> <%= time_ago_in_words(@review.created_at) + " ago" %> </p>



       <div class="flex flex-wrap items-center justify-between">
        

        <% if user_signed_in? && current_user.id == @review.user_id %>
          <div class="pt-4 flex flex-wrap items-center space-x-4">
            <%= link_to edit_review_path(@review), class: "no-underline" do %>
              <%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-400 w-5 h-5 hover:text-orange-600" %>
            <% end %>

            <%= button_to review_path(@review), method: :delete, data: { confirm: "Are you sure you want to delete this review?" },  class: "no-underline block mt-px" do %>
              <%= render_svg "icons/delete", title: "Delete", styles: "fill-current text-gray-400 w-5 h-5 hover:text-orange-600" %>
            <% end %>
          </div>
        <% end %>
      </div>

    <div class="mt-6 pt-6 border-t border-gray-300">
    <% if user_signed_in? %>
      <div id="<%= dom_id(@review) %>_comments_form">
        <%= render "comments/form", comment: Comment.new %>
      </div>
    <% else %>
      <div class="bg-gray-50 rounded p-4 mt-6 text-center">
        <%= link_to "Login to comment", new_user_session_path, class: "text-orange-600 underline" %>
      </div>
    <% end %>

    <h3 id="comment_section" class="font-bold mt-6">Comments</h3>
    <div id="<%= dom_id(@review) %>_comments">
      <% if @review.comments.any? %>
        <%= render @review.comments %>
      <% end %>
    </div>
    </end>

    </div>
  </div>
</li>